'''
Emon and Tintin events have slightly different names
'''

emon_events = {
    "CPU_CLK_UNHALTED.THREAD",
    "CPU_CLK_UNHALTED.REF_TSC",
    "INST_RETIRED.ANY",
    "MEM_INST_RETIRED.ALL_LOADS",
    "MEM_INST_RETIRED.ALL_STORES",
    "L1D.REPLACEMENT",
    "L2_LINES_IN.ALL",
    "IDQ_UOPS_NOT_DELIVERED.CORE",
    "UOPS_ISSUED.ANY",
    "INT_MISC.RECOVERY_CYCLES_ANY",
    "UOPS_RETIRED.RETIRE_SLOTS",
    "CYCLE_ACTIVITY.STALLS_MEM_ANY",
    "EXE_ACTIVITY.BOUND_ON_STORES",
    "EXE_ACTIVITY.1_PORTS_UTIL",
    "EXE_ACTIVITY.2_PORTS_UTIL",
    "EXE_ACTIVITY.EXE_BOUND_0_PORTS",
    "CYCLE_ACTIVITY.STALLS_L1D_MISS",
    "CYCLE_ACTIVITY.STALLS_L2_MISS",
    "CYCLE_ACTIVITY.STALLS_L3_MISS",
    "OFFCORE_REQUESTS_OUTSTANDING.L3_MISS_DEMAND_DATA_RD_GE_6",
    "OFFCORE_REQUESTS_OUTSTANDING.CYCLES_WITH_L3_MISS_DEMAND_DATA_RD"
}

tintin_events = {
    "CPU_CLK_UNHALTED",
    "CYCLE_ACTIVITY.STALLS_L1D_MISS",
    "CYCLE_ACTIVITY.STALLS_L2_MISS",
    "CYCLE_ACTIVITY.STALLS_L3_MISS",
    "CYCLE_ACTIVITY.STALLS_MEM_ANY",
    "EXE_ACTIVITY.1_PORTS_UTIL",
    "EXE_ACTIVITY.2_PORTS_UTIL",
    "EXE_ACTIVITY.BOUND_ON_STORES",
    "EXE_ACTIVITY.EXE_BOUND_0_PORTS",
    "IDQ_UOPS_NOT_DELIVERED.CORE",
    "INST_RETIRED",
    "INT_MISC.RECOVERY_CYCLES_ANY",
    "L1D.REPLACEMENT",
    "L2_LINES_IN.ALL",
    "MEM_INST_RETIRED.ALL_LOADS",
    "MEM_INST_RETIRED.ALL_STORES",
    "OFFCORE_REQUESTS_OUTSTANDING.CYCLES_WITH_L3_MISS_DEMAND_DATA_RD",
    "OFFCORE_REQUESTS_OUTSTANDING.L3_MISS_DEMAND_DATA_RD_GE_6",
    "UOPS_ISSUED.ANY",
    "UOPS_RETIRED.RETIRE_SLOTS",
}